# Generated by Django 2.2.17 on 2021-01-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_task_subtasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ('name',)},
        ),
    ]
